# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 21:19
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(default='', max_length=200)),
                ('companyRole', models.CharField(default='', max_length=200)),
                ('companyLocation', models.CharField(default='', max_length=200)),
                ('joiningDate', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('leavingDate', models.DateField(verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(default='', max_length=200)),
                ('TechnologiesUsed', models.TextField(default='')),
                ('ProjectDescription', models.TextField(default='')),
                ('company', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hello.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(default='', max_length=200)),
                ('courseDuration', models.CharField(default='', max_length=200)),
                ('coursePercentage', models.CharField(default='', max_length=200)),
                ('instituteName', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(default='', max_length=200)),
                ('userbio', models.TextField(default='', max_length=200)),
                ('locality', models.TextField(default='', max_length=200)),
                ('userLocation', models.CharField(default='', max_length=200)),
                ('title', models.CharField(default='', max_length=200)),
                ('linkedinUrl', models.CharField(default='', max_length=200)),
                ('githubUrl', models.CharField(default='', max_length=200)),
                ('emailAddress', models.CharField(default='', max_length=200)),
                ('personalDescription', models.TextField(default='')),
                ('careerObjective', models.TextField(default='')),
                ('fbUrl', models.TextField(default='')),
                ('skypeId', models.CharField(default='', max_length=200)),
                ('mobileNumber', models.CharField(default='', max_length=200)),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(default='', max_length=200)),
                ('TechnologiesUsed', models.TextField(default='')),
                ('ProjectDescription', models.TextField(default='')),
                ('projectLink', models.CharField(default='', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillName', models.CharField(default='', max_length=200)),
                ('skillAwarenessPercent', models.CharField(default='', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Strength',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Person')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commaSeperatedlanguages', models.TextField(default='')),
                ('commaSeperateddatabases', models.TextField(default='')),
                ('commaSeperatedBackEnds', models.TextField(default='')),
                ('commaSeperatedFrontEnds', models.TextField(default='')),
                ('commaSeperatedDevtools', models.TextField(default='')),
                ('commaSeperatedotherLibraries', models.TextField(default='')),
                ('commaSeperatedWebservices', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Person')),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Person'),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Person'),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Person'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Person'),
        ),
    ]
