# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-07 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20170801_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='keywords',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
