# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-12 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_organisationalproject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisationalproject',
            old_name='Project',
            new_name='ProjectDescription',
        ),
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
